sudo: required
services:
  - docker

before_install:
  - docker build -t atharvsushant/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true atharvsushant/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-112229067867"
  bucket_path: "docker-react"
  on:
    branch: master
